In [19]:
from scipy.sparse.data import matrix
import pandas as pd
import numpy as np

In [6]:
from sklearn.preprocessing import MinMaxScaler


In [9]:
import pandas as pd

In [12]:
ds=pd.read_csv('dataset_website.csv')
ds.head()

index  having_IPhaving_IP_Address  URLURL_Length  Shortining_Service  \
0      1                          -1              1                   1   
1      2                           1              1                   1   
2      3                           1              0                   1   
3      4                           1              0                   1   
4      5                           1              0                  -1   

   having_At_Symbol  double_slash_redirecting  Prefix_Suffix  \
0                 1                        -1             -1   
1                 1                         1             -1   
2                 1                         1             -1   
3                 1                         1             -1   
4                 1                         1             -1   

   having_Sub_Domain  SSLfinal_State  Domain_registeration_length  ...  \
0                 -1              -1                           -1  ...   
1                  0               1                           -1  ...   
2                 -1              -1                           -1  ...   
3                 -1              -1                            1  ...   
4                  1               1                           -1  ...   

   popUpWidnow  Iframe  age_of_domain  DNSRecord  web_traffic  Page_Rank  \
0            1       1             -1         -1           -1         -1   
1            1       1             -1         -1            0         -1   
2            1       1              1         -1            1         -1   
3            1       1             -1         -1            1         -1   
4           -1       1             -1         -1            0         -1   

   Google_Index  Links_pointing_to_page  Statistical_report  Result  
0             1                       1                  -1      -1  
1             1                       1                   1      -1  
2             1                       0                  -1      -1  
3             1                      -1                   1      -1  
4             1                       1                   1       1  

[5 rows x 32 columns]

In [15]:
ds.info()
ds.isnull

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11055 entries, 0 to 11054
Data columns (total 32 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   index                        11055 non-null  int64
 1   having_IPhaving_IP_Address   11055 non-null  int64
 2   URLURL_Length                11055 non-null  int64
 3   Shortining_Service           11055 non-null  int64
 4   having_At_Symbol             11055 non-null  int64
 5   double_slash_redirecting     11055 non-null  int64
 6   Prefix_Suffix                11055 non-null  int64
 7   having_Sub_Domain            11055 non-null  int64
 8   SSLfinal_State               11055 non-null  int64
 9   Domain_registeration_length  11055 non-null  int64
 10  Favicon                      11055 non-null  int64
 11  port                         11055 non-null  int64
 12  HTTPS_token                  11055 non-null  int64
 13  Request_URL                  11055 non-null  i

<bound method DataFrame.isnull of        index  having_IPhaving_IP_Address  URLURL_Length  Shortining_Service  \
0          1                          -1              1                   1   
1          2                           1              1                   1   
2          3                           1              0                   1   
3          4                           1              0                   1   
4          5                           1              0                  -1   
...      ...                         ...            ...                 ...   
11050  11051                           1             -1                   1   
11051  11052                          -1              1                   1   
11052  11053                           1             -1                   1   
11053  11054                          -1             -1                   1   
11054  11055                          -1             -1                   1   

       having_At_

In [71]:
x=ds.iloc[:, 0:15].values
y=ds.iloc[:, 1].values
print(x,y)

[[    1    -1     1 ...    -1     1    -1]
 [    2     1     1 ...    -1     1     0]
 [    3     1     0 ...    -1     1     0]
 ...
 [11053     1    -1 ...     1     1     0]
 [11054    -1    -1 ...     1    -1    -1]
 [11055    -1    -1 ...     1    -1    -1]] [-1  1  1 ...  1 -1 -1]


In [72]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.05,random_state=0)

In [73]:
x_train

array([[ 1377,     1,    -1, ...,     1,     1,     0],
       [ 7458,     1,    -1, ...,     1,    -1,    -1],
       [ 7070,     1,    -1, ...,    -1,    -1,     1],
       ...,
       [ 9846,    -1,     1, ...,     1,     1,     1],
       [10800,    -1,    -1, ...,     1,     1,    -1],
       [ 2733,     1,    -1, ...,     1,     1,    -1]])

In [74]:
y_train

array([ 1,  1,  1, ..., -1, -1,  1])

In [75]:
x_test

array([[ 227,    1,   -1, ...,    1,   -1,   -1],
       [2253,    1,   -1, ...,    1,    1,   -1],
       [2647,    1,   -1, ...,    1,    1,    0],
       ...,
       [8751,    1,    1, ...,    1,    1,    0],
       [8611,   -1,    1, ...,    1,    1,   -1],
       [7447,    1,   -1, ...,    1,    1,    0]])

In [76]:
y_test

array([ 1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1, -1, -1,  1,
        1,  1,  1, -1,  1,  1,  1,  1,  1, -1, -1,  1, -1, -1, -1, -1,  1,
       -1, -1, -1,  1, -1, -1,  1,  1,  1, -1,  1,  1,  1,  1, -1,  1,  1,
        1,  1,  1,  1, -1, -1, -1, -1,  1,  1,  1, -1,  1,  1, -1,  1,  1,
        1,  1, -1,  1,  1,  1, -1,  1,  1, -1, -1, -1, -1, -1,  1,  1,  1,
        1,  1,  1,  1,  1,  1, -1,  1, -1,  1,  1,  1,  1, -1,  1, -1, -1,
        1,  1, -1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1, -1, -1,  1,
        1, -1,  1,  1,  1, -1, -1, -1,  1, -1,  1, -1,  1,  1,  1, -1, -1,
       -1,  1,  1, -1, -1,  1,  1,  1, -1,  1, -1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1, -1, -1,  1, -1, -1,  1, -1,  1, -1,  1, -1, -1,
       -1, -1, -1,  1,  1,  1,  1, -1,  1, -1, -1, -1,  1,  1,  1,  1,  1,
        1,  1, -1,  1, -1,  1,  1,  1,  1, -1,  1,  1,  1, -1, -1,  1, -1,
        1, -1,  1, -1, -1,  1,  1,  1,  1,  1, -1, -1, -1, -1,  1,  1, -1,
       -1,  1,  1,  1,  1